Included develop and cicd-aide

diff --git a/environment/resources/10_gitea/setup-job.yaml b/environment/resources/10_gitea/setup-job.yaml
--- a/environment/resources/10_gitea/setup-job.yaml
+++ b/environment/resources/10_gitea/setup-job.yaml
@@ -35,7 +35,44 @@ spec:
             -d '{"username":"gitea","password":"openshift","retype":"openshift","email":"gitea@gitea.com","send_notify":false}' \
             -H "Content-Type: application/json" \
             http://$GITEA_HOSTNAME/user/sign_up
-          
+
+          echo "-- Creating developer user --"
+
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
+            -u gitea:openshift \
+            -d '{"develop@example.com","full_name": "develop","login_name": "develop","must_change_password": false,"password": "develop""restricted": true,"send_notify": false,"username": "develop"}' \
+            -H "Content-Type: application/json" \
+            http://$GITEA_HOSTNAME/api/v1/admin/users)
+
+          if [ "$RESPONSE" != "201" ]; then
+              echo "Error creating developer user, error code: $RESPONSE"
+              exit 1
+          fi
+
+          echo "-- Creating cicd-aide user as admin --"
+
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
+            -u gitea:openshift \
+            -d '{"cicd-aide@example.com","full_name": "cicd-aide","login_name": "cicd-aide","must_change_password": false,"password": "cicd-aide""restricted": true,"send_notify": false,"username": "cicd-aide"}' \
+            -H "Content-Type: application/json" \
+            http://$GITEA_HOSTNAME/api/v1/admin/users)
+
+          if [ "$RESPONSE" != "201" ]; then
+              echo "Error creating cicd aide user, error code: $RESPONSE"
+              exit 1
+          fi
+
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X PATCH \
+            -u gitea:openshift \
+            -d '{"admin": true,"login_name": "cicd-aide"}' \
+            -H "Content-Type: application/json" \
+            http://$GITEA_HOSTNAME/api/v1/admin/users/cicd-aide)
+
+          if [ "$RESPONSE" != "201" ]; then
+              echo "Error making cicd aide admin, error code: $RESPONSE"
+              exit 1
+          fi
+                   
           echo "-- Creating demo repository --"
           git clone -b argo_instalation https://github.com/clbartolome/automation-developer-hub   
           echo "------------------------------"   
@@ -49,6 +86,18 @@ spec:
 
           if [ "$RESPONSE" != "201" ]; then
               echo "Error creating repository, error code: $RESPONSE"
+              exit 1
+          fi
+
+          echo "-- Making developer user collaborator on applications collection repository --"
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X PUT \
+            -u gitea:openshift \
+            -d '{"permission": "write"}' \
+            -H "Content-Type: application/json" \
+            http://$GITEA_HOSTNAME/api/v1/repos/gitea/operations.applications/collaborators/develop)
+
+          if [ "$RESPONSE" != "201" ]; then
+              echo "Error making colaborator, error code: $RESPONSE"
               exit 1
           fi
 
